;;; Automatically generated by ‘recentf’ on Sun Jun 14 22:47:38 2020.

(setq recentf-list
      '(
        "/home/aidanjbailey/Academic/CSC3022H/Handins/Assignments/Template/src/driver.cpp"
        "/home/aidanjbailey/.emacs.d/var/treemacs/persist.org"
        "/home/aidanjbailey/Academic/CSC3022H/Handins/Assignments/XOrSolver/src/XORSolver.cpp"
        "/home/aidanjbailey/Academic/CSC3022H/Handins/Assignments/XOrSolver/src/Driver.cpp"
        "/home/aidanjbailey/Academic/CSC3022H/Handins/Assignments/Assignment7/src/PerceptronGraph.cpp"
        "/home/aidanjbailey/Academic/CSC3022H/Handins/Assignments/Assignment7/src/Driver.cpp"
        "/home/aidanjbailey/Academic/CSC3022H/Handins/Assignments/Assignment7/src/ANNHelper.cpp"
        "/home/aidanjbailey/Academic/CSC3022H/Handins/Assignments/Assignment7/include/ANNHelper.hpp"
        "/usr/include/c++/10.1.0/bits/stl_vector.h"
        "/home/aidanjbailey/Academic/CSC3022H/Handins/Assignments/Assignment7/Makefile"
        "/home/aidanjbailey/Academic/CSC3022H/Handins/Assignments/Assignment6/src/GridWorld.cpp"
        "/home/aidanjbailey/Academic/CSC3022H/Handins/Assignments/Assignment6/include/GridWorld.hpp"
        "/home/aidanjbailey/Academic/EEE2050F/Notes/Quiz5.org"
        "/home/aidanjbailey/Academic/EEE2050F/Slides/8_ About STM32F051C6.pdf"
        "/home/aidanjbailey/.emacs.d/general-spacemap.el"
        "/home/aidanjbailey/.emacs.d/package-vars.el"
        "/home/aidanjbailey/.emacs.d/package-list.el"
        "/home/aidanjbailey/.emacs.d/package-hooks.el"
        "/home/aidanjbailey/.emacs.d/init.el"
        "/home/aidanjbailey/order"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
