;;; Automatically generated by ‘recentf’ on Tue May 19 11:40:34 2020.

(setq recentf-list
      '(
        "/home/aidanjbailey/Academic/CSC3022H/Handins/Labs/Practice/Lab3/Tutorial 3.pdf"
        "/home/aidanjbailey/Academic/CSC3022H/Handins/Labs/Practice/Lab2/consolidation_two.cpp"
        "/home/aidanjbailey/Academic/CSC3022H/Handins/Labs/Practice/Lab2/menu.txt"
        "/home/aidanjbailey/Academic/CSC3022H/Handins/Labs/Practice/Lab1/Lab_1.pdf"
        "/home/aidanjbailey/Academic/CSC3022H/Handins/Assignments/Assignment6/src/VIHelper.cpp"
        "/home/aidanjbailey/Academic/CSC3022H/Handins/Assignments/Assignment6/include/VIHelper.hpp"
        "/home/aidanjbailey/Academic/CSC3022H/Handins/Assignments/Assignment6/src/GridWorld.cpp"
        "/home/aidanjbailey/Academic/CSC3022H/Handins/Assignments/Assignment6/include/GridWorld.hpp"
        "/home/aidanjbailey/Academic/CSC3022H/Handins/Assignments/Assignment6/src/Driver.cpp"
        "/home/aidanjbailey/Academic/CSC3022H/Handins/Assignments/Assignment6/Makefile"
        "/home/aidanjbailey/Academic/CSC3022H/Handins/Assignments/Assignment6/.ccls-cache/@home@aidanjbailey@Academic@CSC3022H@Handins@Assignments@Assignment6/src@VIHelper.cpp"
        "/home/aidanjbailey/.emacs.d/elpa/transient-20200517.2038/transient-autoloads.el"
        "/home/aidanjbailey/.emacs.d/elpa/git-commit-20200516.2016/git-commit-autoloads.el"
        "/home/aidanjbailey/.emacs.d/elpa/evil-20200516.1740/evil-autoloads.el"
        "/home/aidanjbailey/.emacs.d/elpa/magit-20200517.1537/magit-autoloads.el"
        "/home/aidanjbailey/.emacs.d/elpa/company-20200510.1614/company-autoloads.el"
        "/home/aidanjbailey/Academic/CSC3022H/Handins/Assignments/Assignment6/.gitignore"
        "/home/aidanjbailey/.emacs.d/var/treemacs/persist.org"
        "/home/aidanjbailey/Academic/CSC3022H/Notes/ml.org"
        "/home/aidanjbailey/Academic/CSC3022H/Slides/ml/2020-ML-Lec8-RLII.pdf"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
